# Generated by Django 6.0 on 2025-12-05 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='wallet_balance',
        ),
    ]
